### ISSUE TITLE
Reporting - error when selecting poi layer in reachability

### ISSUE THREAD

**Issue by t16h05008** [KomMonitor/web-client#24]
In the reachability template, the first step is to select a poi layer. This only works once. If the user changes the selection afterwards, the loading screen is infinite.
The error seems to be thrown because of an undefined object property. Why it is undefined needs to be looked into.

![grafik](https://user-images.githubusercontent.com/49350695/188606893-baa56c74-3b74-4bc1-b767-59e17c5c84ee.png)

**Comment by cDanowski** [comment]
hey, I could not reproduce this on my local system. While trying to test it on a deployed instance, some undeclared variable issues popped up. Will report again here once I tested it

**Comment by cDanowski** [comment]
deployed on https://demo.kommonitor.de/#!/

However, the error is not reproducable. Maybe occured due to false POI data?

@t16h05008 do you have time to recheck it with your exact click workflow? then please pull latest develop/master/reporting-tool branch and try again

**Comment by t16h05008** [comment]
I tried to reproduce the bug both with the "old" version from [72d94c5] and after the recent changes and couldn't reproduce it either. Maybe I had some local uncommited changes which lead to the bug and I reverted them later. That's the only reason I can think of for now.
I think it's safe to close this issue. Anyway, thanks for looking into it.
