### ISSUE TITLE
URL Feld im Batch Update wird ignoriert und nicht richtig gesetzt

### ISSUE THREAD

**Issue by cDanowski** [KomMonitor/web-client#34]
bei dem Versuch, die Batch-Update Funktion des Kommonitors zu nutzen, bin ich auf ein Problem gestoßen. Und zwar gelingt es mir nicht, extern auf unserem Webserver gehostete csv-Dateien über eine URL im Kommonitor einzulesen. Ich vermute, dass das URL-Feld in der Mapping-Tabelle des Batch-Updates nicht korrekt beschrieben und ausgelesen wird.

Ich versuche mal in Kürze zu beschreiben, wie ich auf die Vermutung gekommen bin:

- Wenn ich das Indikator-Mapping von Hand in der Weboberfläche eintrage, den Datenquelltyp auf "HTTP" setze und die URL der .csv-Datei einfüge, resultiert dies in einem 500er Server-Status ohne konkrete Fehlermeldung.
- Wenn ich die gleiche csv-Datei über den Datenquelltyp "FILE" hochlade, funktioniert alles. Die csv-Datei selbst scheint also in Ordnung zu sein.
- Der Link ([z.B. http://hits.herne.de/hits/kommonitor/dat_id_stadt.csv](http://mg00.hs-bochum.de:32224/?dmVyPTEuMDAxJiYzZWVjZDdjMjhmNjQ2MzhjND02M0Y2MzQ0MV8xOTQ5OF8xOTYxM18xJiY1ZGNlOTRjMzIyMjVjMjk9MTIzMyYmdXJsPWh0dHAlM0ElMkYlMkZoaXRzJTJFaGVybmUlMkVkZSUyRmhpdHMlMkZrb21tb25pdG9yJTJGZGF0JTVGaWQlNUZzdGFkdCUyRWNzdg==)) ist ebenfalls korrekt, denn die csv-Datei kann sowohl über den Webbrowser heruntergeladen als auch in R eingelesen werden.

Zunächst habe ich daraus geschlossen, dass die Kommonitor-Instanz auf dem RVR-Server aus unerfindlichen Gründen daran scheitert, die csv-Datei von unserem Webserver zu lesen. Allerdings ist mir dann folgendes aufgefallen:

- Wenn ich eine händisch angelegte Mappingtabelle über den blauen Button rechts speichere, ist das URL-Feld in der exportierten Datei ein leerer String. Egal, was im URL-Feld stand.
- Daraufhin habe ich den umgekehrten Fall probiert: Ich habe die exportierte Mappingtabelle um einen Eintrag im URL-Feld ergänzt und wieder importiert. Auch hier werden alle Felder eingelesen, bis auf das URL-Feld. Das erscheint nach dem Import erneut leer.

Deswegen vermute ich, dass das URL-Feld selbst fehlerhaft ist, sodass Einträge jeglicher Art ignoriert werden und stattdessen ein leerer String übergeben wird.

**Comment by t16h05008** [comment]
Ich habe mal nachgesehen und konnte den Fehler (hoffentlich) beheben. Der Commit ist im Branch [feature/batchUpdate](https://github.com/KomMonitor/web-client/compare/feature/batchUpdate).
Jedenfalls konnte ich danach eine Batch-Liste exportieren und Importieren, wobei der URL-Parameter wieder korrekt gesetzt wurde. 

Ein Update habe ich mangels geeigneter Test-Daten aber nicht ausgeführt. Die Methode, in der der Fehler war, wird aber auch dort aufgerufen. Daher stehen die Chancen nicht schlecht, dass das Update nun auch funktionieren sollte. Wenn nicht schau ich mir das nochmal genauer an.

**Comment by cDanowski** [comment]
@t16h05008 witzig, ich habe mich heute Abend auch dran gesetzt.
Trotzdem danke fürs nachschauen und Eingreifen. Sollte erneut ein Fehler diesbezüglich aufkommen, schauen wir noch einmal drauf.
