### ISSUE TITLE
Wertebereich Filter + Räumliche Filter

### ISSUE THREAD

**Issue by mschonlau** [KomMonitor/web-client#53]
Aktuelle Version des Client bei uns 2.1.16

1. Wertebereich Filter
Der Wert zum freien Eintrag und der Slider synchronisieren sich nicht mehr
 
![grafik](https://github.com/KomMonitor/web-client/assets/53268242/57d4f349-a099-442d-b6a3-5a1e93b55f3a)

2. Räumliche Filter
Bei der Auswahl einer Raumebene wird die Auswahlliste der verfügbaren Raumeinheiten nicht aktualisiert
Die aktuell gewählte Raumebene des Indikators sind die Wohnviertel. Bei einem Wechsel der Raumebene wird die Dropdownliste aktualisiert, aber nicht die Auswahlliste.
Ein Klick auf "Selektion zurücksetzen" führt dann dazu, dass immer nur die übergeordnete Raumeinheit angezeigt wird.

![grafik](https://github.com/KomMonitor/web-client/assets/53268242/c60ad3c1-04c1-422a-ad35-3ec739354f93)

**Comment by cDanowski** [comment]
since release 3.0.0. both issues were fixed.
