### ISSUE TITLE
Edit SingleFeatureRecord

### ISSUE THREAD

**Issue by mschonlau** [KomMonitor/web-client#55]
Hallo zusammen,

bei uns im Client tritt in der Adminoberfläche folgender Fehler auf beim editieren einzelner Feature-Einträge:

![grafik](https://github.com/KomMonitor/web-client/assets/53268242/27203227-c2ff-4d6d-a617-9dee3ba937cf)

Das Feature nutzen wir bislang eher selten, aber es fiel heute zufällig auf.

Beste Grüße
Marcel

**Comment by SebaDro** [comment]
Hi @mschonlau . Tritt das Problem regelmäßig oder nur sporadisch auf? Lässt sich der Fehler ggf. nachstellen?

**Comment by mschonlau** [comment]
Hi, also ich habe es eben nochmal getestet und den Fehler nur bei Indikatoren entdeckt. Da tritt er aber grundsätzlich immer auf. Bei Georessourcen tritt der Fehler nicht auf.

**Comment by SebaDro** [comment]
Sorry für die späte Rückmeldung. Tatsächlich konnte ich die Fehlermeldung mittlerweile selber nachstellen und ich habe eine Vermutung, was das Problem sein könnte. In meinen Tests ist der Fehler beim Update eines einzelnen Features bisher ausschließlich bei Indikatordatensätzen aufgetreten, die neben den verpflichtenden Zeitstempel- und Indikatorparametern zusätzlich auch weitere Sachdaten aufweisen. 

Könntest du das ggf. einmal bei einem deiner Datensätze verifizieren? Hierzu wäre es super, wenn du ggf. einmal den Response der Data Management API nach einem Klick auf "Zeige alle Features" in der Admin-Oberfläche bereitstellen könntest. In der Netzwerkconsole des Browsers ist das der Request, der auf `/without-geometry` endet. In deinem Screenshot oben wäre das der GET Request, der an zweiter Stelle auftaucht.

**Comment by mschonlau** [comment]
So, bin jetzt auch wieder dazu gekommmmen. Bei uns haben alle Indikatoren durch die Raumeibenen noch weitere Sachdaten, insofern passt das. Hier eine Beispiel-Response:

``` json
[
	{
		"fid": "1",
		"SHAPE_LEN": "23852.2102331999995",
		"DATE_2022-12-31": "2989",
		"OBJECTID_1": "1",
		"spatialUnitFeatureName": "I",
		"SHAPE_AREA": "15578131.9829999991",
		"NAME": "I",
		"OBJECTID": "1",
		"arisenFrom": null,
		"ID": "1",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "1",
		"validEndDate": null
	},
	{
		"fid": "2",
		"SHAPE_LEN": "21265.8368002999996",
		"DATE_2022-12-31": "5216",
		"OBJECTID_1": "2",
		"spatialUnitFeatureName": "II",
		"SHAPE_AREA": "13480337.8247999996",
		"NAME": "II",
		"OBJECTID": "2",
		"arisenFrom": null,
		"ID": "2",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "2",
		"validEndDate": null
	},
	{
		"fid": "3",
		"SHAPE_LEN": "25056.5086527999993",
		"DATE_2022-12-31": "6961",
		"OBJECTID_1": "3",
		"spatialUnitFeatureName": "III",
		"SHAPE_AREA": "16530190.2828000002",
		"NAME": "III",
		"OBJECTID": "3",
		"arisenFrom": null,
		"ID": "3",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "3",
		"validEndDate": null
	},
	{
		"fid": "4",
		"SHAPE_LEN": "24665.5052738999984",
		"DATE_2022-12-31": "4730",
		"OBJECTID_1": "4",
		"spatialUnitFeatureName": "IV",
		"SHAPE_AREA": "24512278.4800000004",
		"NAME": "IV",
		"OBJECTID": "4",
		"arisenFrom": null,
		"ID": "4",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "4",
		"validEndDate": null
	},
	{
		"fid": "5",
		"SHAPE_LEN": "24169.8021532999992",
		"DATE_2022-12-31": "2569",
		"OBJECTID_1": "5",
		"spatialUnitFeatureName": "V",
		"SHAPE_AREA": "18218242.5916000009",
		"NAME": "V",
		"OBJECTID": "5",
		"arisenFrom": null,
		"ID": "5",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "5",
		"validEndDate": null
	},
	{
		"fid": "6",
		"SHAPE_LEN": "18206.5348216999992",
		"DATE_2022-12-31": "2353",
		"OBJECTID_1": "6",
		"spatialUnitFeatureName": "VI",
		"SHAPE_AREA": "12984672.9689000007",
		"NAME": "VI",
		"OBJECTID": "6",
		"arisenFrom": null,
		"ID": "6",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "6",
		"validEndDate": null
	},
	{
		"fid": "7",
		"SHAPE_LEN": "25178.9804183999986",
		"DATE_2022-12-31": "4266",
		"OBJECTID_1": "7",
		"spatialUnitFeatureName": "VII",
		"SHAPE_AREA": "20884390.3203000017",
		"NAME": "VII",
		"OBJECTID": "7",
		"arisenFrom": null,
		"ID": "7",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "7",
		"validEndDate": null
	},
	{
		"fid": "8",
		"SHAPE_LEN": "36901.1126527000015",
		"DATE_2022-12-31": "3984",
		"OBJECTID_1": "8",
		"spatialUnitFeatureName": "VIII",
		"SHAPE_AREA": "33106074.8464000002",
		"NAME": "VIII",
		"OBJECTID": "8",
		"arisenFrom": null,
		"ID": "8",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "8",
		"validEndDate": null
	},
	{
		"fid": "9",
		"SHAPE_LEN": "38869.4519172",
		"DATE_2022-12-31": "3885",
		"OBJECTID_1": "9",
		"spatialUnitFeatureName": "IX",
		"SHAPE_AREA": "54974326.384800002",
		"NAME": "IX",
		"OBJECTID": "9",
		"arisenFrom": null,
		"ID": "9",
		"validStartDate": "2000-01-01 00:00:00",
		"spatialUnitFeatureId": "9",
		"validEndDate": null
	}
]
```

**Comment by SebaDro** [comment]
Danke für's Prüfen. Dann scheint es tatsächlich ein Problem bei Indikatoren mit angehängten Sachdaten zu geben. Mein Lösungsansatz:
* Anpassen des betroffenen Endpoints, sodass Indikatoren standardmäßig ohne Sachdaten zurückgegeben werden
* Einführung eines neuen Endpunkts bzw. Request-Parameters, mit der die API angewiesen werden kann, auch Sachdaten zu Indikatoren zu liefern
* Überprüfen des Web Clients, an welchen Stellen der neue Endpunkt, bzw. der Request mit ergänztem Request Parameter erfolgen muss

Was meint ihr?

**Comment by cDanowski** [comment]
hi, 

sorry for the late response. This issue was fixed in c998015 by removing all non-timestamp related attributes from the submitted feature table record. Thus this issue was removed since release v 3.0.4 .

thanks for spotting it.
