### ISSUE TITLE
Fehlerhafte Beschreibung Schwellwertklassifizierung

### ISSUE THREAD

**Issue by SebaDro** [KomMonitor/web-client#58]
**Fehlerbeschreibung**
Bei der Schwellwertklassifizierung ist die Beschreibung der Kategorie der Features, die unterhalb des Schwellwerts liegen, fehlerhaft.
Statt `Features, deren Indikatorwert unter dem Schwellenwert liegt (Violett-Töne)` sollte es heißen `Features, deren Indikatorwert unter dem Schwellenwert liegt (Blau-Töne)`, um der in der Karte dargestellten Farbgebung zu entsprechen. Alternativ könnte auch die Farbgebung in der Karte auf Violett-Töne geändert werden.

![image](https://github.com/KomMonitor/web-client/assets/18207870/5ab7249b-fb4d-4408-b762-94b48a465837)

**Comment by cDanowski** [comment]
thanks for spotting that bogus description.

it has been there for years. 

fixed in b45cccb
