### ISSUE TITLE
Definierte Standard-Klassengrenzen werden überschrieben

### ISSUE THREAD

**Issue by mschonlau** [KomMonitor/web-client#62]
Wir haben einen Status-Inidkator erstellt, dessen Wertebereich von <= -3000 bis >= 1000 läuft und dafür folgende Standardklassifizierung definiert:

![grafik](https://github.com/KomMonitor/web-client/assets/53268242/2b1ab8c0-85a6-4ac6-8440-e3619e89bb07)

Dort sieht man bereits ein erstes Problem, da die '0' nicht als Klassengrenze verwendet werden kann:

![grafik](https://github.com/KomMonitor/web-client/assets/53268242/2417dbfb-06e3-43a3-ae16-40ca4f0df3e7)

Wir haben dann für Testzweicke 0,1 eingetragen. Im Webclient wird zwar angezeigt, dass die Methode 'Regionaler Standard' verwendet wird, allerdings in diesem Fall durch die Klassifizierung eines Dynamik-Indikators überschrieben.

![grafik](https://github.com/KomMonitor/web-client/assets/53268242/3fee69c8-7105-43cc-8595-500cfb7fdc91)

In Publikationen wird der Indikator 'CVII' durch eine divergierende Farbskala dargestellt. Hier benötigen wir also, falls Werte vom Negativen bis ins Positive verlaufen, auch divergierende Farbskalen zur Auswahl. Insbesondere für Indikatoren im Umweltbereich oder Indizes generell können diese Anwendungsfälle häufiger auftreten und für eine sinnvolle Darstellung benötigt werden.

**Comment by mschonlau** [comment]
Kleine Ergänzung zu diesem Issue: Man sieht es bereits auf dem letzten Screenshot. Wo ist der Button (de)aktivieren der Ausreißerdarstellung geblieben? Der müsste doch auch in dem Menü "Klassifikation anpassen" untergebracht werden, oder? Danach wurde bei uns auf jeden Fall bereits gefragt. In der Config habe ich gesehen, dass es den Parameter `window.__env.useOutlierDetectionOnIndicator = true;` zumindest immer noch gibt.

**Comment by sanwarhier** [comment]
Vielen Dank für die Anmerkungen.

Die 0 kann jetzt verwendet werden und wird in der Legende korrekt angezeigt. ed4d535c26b9413b7e9476fa9108aaed3f7db294
Außerdem wird die regionale Standard-Klassifizierung nun auch angewendet, wenn negative Wertebereiche vorhanden sind, dafür werden die Standard-Farbspektren für negative und positive Werte benutzt. 412857013cc1675c6dae8066007dd8e771423cc3 a1390966a0fbd28f73e462cec7479c85a3ec6e65

Der Ausreißer-Schalter ist nun wieder verfügbar, wenn keine manuelle oder regionale Standard-Klassifikation ausgewählt ist. d320642807b37b9423722d9b05a85caf86bd5001 1e5512e0c110219e75a038e90219d85a1b8c20e8
