### ISSUE TITLE
Infinite loading screen in der sidebar 

### ISSUE THREAD

**Issue by mschonlau** [KomMonitor/web-client#63]
Webclient Version: 3.0.3

Nach dem Anlegen eines neuen Indikators, läd der Indikator zwar ganz normal, anscheinend gibt es aber ein Problem bei der Initialisierung der Diagramme
![grafik](https://github.com/user-attachments/assets/e2094edf-8f1c-42cc-be3d-68fe9771c99f)

Dann blockiert das div `class="loading-overlay-sidebar-small"` die Sidebar und ein Wechsel des Indikators ist nicht mehr möglich.

Fehlermeldung in der Konsole:
> Uncaught TypeError: e[0] is undefined
    aB https://km.essen.de/dependencies/echarts/echarts.min.js:2
    H https://km.essen.de/dependencies/echarts/echarts.min.js:2
    B https://km.essen.de/dependencies/echarts/echarts.min.js:2
    u https://km.essen.de/dependencies/echarts/echarts.min.js:2
    renderSeries https://km.essen.de/dependencies/echarts/echarts.min.js:2
    render https://km.essen.de/dependencies/echarts/echarts.min.js:2
    eachSeries https://km.essen.de/dependencies/echarts/echarts.min.js:2
    E https://km.essen.de/dependencies/echarts/echarts.min.js:2
    eachSeries https://km.essen.de/dependencies/echarts/echarts.min.js:2
    render https://km.essen.de/dependencies/echarts/echarts.min.js:2
    Ev https://km.essen.de/dependencies/echarts/echarts.min.js:2
    E https://km.essen.de/dependencies/echarts/echarts.min.js:2
    Ev https://km.essen.de/dependencies/echarts/echarts.min.js:2
    Nv https://km.essen.de/dependencies/echarts/echarts.min.js:2
    update https://km.essen.de/dependencies/echarts/echarts.min.js:2
    resize https://km.essen.de/dependencies/echarts/echarts.min.js:2
    controller https://km.essen.de/kommonitor-client.min.js:3
    setTimeout handler*.controller</< https://km.essen.de/kommonitor-client.min.js:3
    $broadcast Angular
    onSidebarDiagramsClick https://km.essen.de/kommonitor-client.min.js:3
    Angular 5
    jQuery 8
    Angular 24
echarts.min.js:2:913180
    aB https://km.essen.de/dependencies/echarts/echarts.min.js:2
    H https://km.essen.de/dependencies/echarts/echarts.min.js:2
    filter self-hosted:241
    B https://km.essen.de/dependencies/echarts/echarts.min.js:2
    u https://km.essen.de/dependencies/echarts/echarts.min.js:2
    renderSeries https://km.essen.de/dependencies/echarts/echarts.min.js:2
    render https://km.essen.de/dependencies/echarts/echarts.min.js:2
    eachSeries https://km.essen.de/dependencies/echarts/echarts.min.js:2
    forEach self-hosted:203
    E https://km.essen.de/dependencies/echarts/echarts.min.js:2
    eachSeries https://km.essen.de/dependencies/echarts/echarts.min.js:2
    render https://km.essen.de/dependencies/echarts/echarts.min.js:2
    Ev https://km.essen.de/dependencies/echarts/echarts.min.js:2
    forEach self-hosted:203
    E https://km.essen.de/dependencies/echarts/echarts.min.js:2
    Ev https://km.essen.de/dependencies/echarts/echarts.min.js:2
    Nv https://km.essen.de/dependencies/echarts/echarts.min.js:2
    update https://km.essen.de/dependencies/echarts/echarts.min.js:2
    resize https://km.essen.de/dependencies/echarts/echarts.min.js:2
    controller https://km.essen.de/kommonitor-client.min.js:3
    (Async: setTimeout handler)
    controller https://km.essen.de/kommonitor-client.min.js:3
    $broadcast Angular
    onSidebarDiagramsClick https://km.essen.de/kommonitor-client.min.js:3
    Angular 5
    jQuery 8
    Angular 24

**Comment by cDanowski** [comment]
hey, sorry for the late response.

in bc363f3 this issue was already fixed and released in 3.0.4. 

However, we currently work on some other bugs still existing in v 3.0.5 (reporting und reachability). Once they are released in v 3.0.6 we will inform all administrators again to update. 

The release of v 3.0.6 should happen in this week.

Greetings, Christian
