### ISSUE TITLE
Wrong indicator color schema after reachability analysis

### ISSUE THREAD

**Issue by SebaDro** [KomMonitor/web-client#64]
## Description
After your have calculated a reachability analysis with an indicator that has a different color schema then the selected indicator in the main map, the legend will be displayed with color schema of the indicator from the reachability analysis. 

## How to reproduce
1. Select an arbitrary indicator in the main map view. You can see a color scheme with blueish levels
![image](https://github.com/user-attachments/assets/8d37525f-96fb-4796-8bfd-75e8025291db)

2. Calculate a reachability analysis with an indicator that has a different color scheme, e.g. with lila color levels
![image](https://github.com/user-attachments/assets/3db2981f-96e9-47ba-bcc8-0d822bf856c1)

3. After the calculation go back to the main map page. You will see the indicator from step one but with the color scheme in the legend of the indicator from step two
![image](https://github.com/user-attachments/assets/2962dafa-cb61-4e55-a051-64e7f9149669)

**Comment by cDanowski** [comment]
even worse, not only the color scheme is wrong. INstead all the numbers (thus the whole legend) is wrong and misleading.

will fix it asap

**Comment by SebaDro** [comment]
A workaround until it is fixed: reselecting the same indicator in the selection menu will reload the correct legend, again.
